#pragma once
#include <stdlib.h>     /* srand, rand */
#include <time.h>       /* time */
#include <string>
#include <vector>
#include <algorithm>
using namespace std;
int generateNumber(int inferior, int superior){
    /* initialize random seed: */
    srand(time(NULL));

    /* generate secret number between inferior and superior: */
    int num = rand() % superior + inferior;

    return num;
}

string* crearNombre(int num){
    string* arr = new string[num];
vector <string> nombres = { "Abbot",
"Abdul",
"Abel",
"Acton",
"Adele",
"Adria",
"Aidan",
"Alden",
"Alec",
"Alexander",
"Alfonso",
"Althea",
"Amal",
"Amery",
"Amos",
"Andrew",
"April",
"Armando",
"Arsenio",
"Arthur",
"Ashton",
"Audra",
"August",
"Axel",
"Baker",
"Barclay",
"Barrett",
"Beau",
"Beck",
"Benedict",
"Berk",
"Bernard",
"Bevis",
"Boris",
"Brady",
"Branden",
"Brandon",
"Brent",
"Brian",
"Britanney",
"Brock",
"Brody",
"Bruce",
"Burton",
"Byron",
"Byron",
"Cailin",
"Caldwell",
"Caleb",
"Callum",
"Calvin",
"Camden",
"Camilla",
"Candice",
"Carl",
"Carly",
"Carson",
"Carter",
"Chancellor",
"Chandler",
"Channing",
"Charles",
"Chase",
"Christian",
"Ciaran",
"Claire",
"Clark",
"Clarke",
"Clayton",
"Clementine",
"Cole",
"Colin",
"Colorado",
"Colt",
"Colton",
"Conan",
"Connor",
"Cora",
"Craig",
"Curran",
"Cyrus",
"Dale",
"Damian",
"Dane",
"Daquan",
"David",
"Dean",
"Declan",
"Dennis",
"Denton",
"Derek",
"Destiny",
"Devin",
"Dexter",
"Dolan",
"Dominic",
"Donovan",
"Dorian",
"Dorothy",
"Drew",
"Driscoll",
"Duncan",
"Dylan",
"Eagan",
"Eaton",
"Edan",
"Elliott",
"Elton",
"Emerson",
"Emery",
"Erica",
"Erich",
"Ethan",
"Ezekiel",
"Fay",
"Felicia",
"Felix",
"Ferris",
"Finn",
"Flynn",
"Francis",
"Freya",
"Gabriel",
"Galena",
"Gannon",
"Garrett",
"Garrison",
"Garth",
"Geoffrey",
"George",
"Germane",
"Giacomo",
"Graham",
"Graiden",
"Graiden",
"Grant",
"Griffith",
"Hamish",
"Hammett",
"Harding",
"Harrison",
"Hasad",
"Hashim",
"Haviva",
"Hayfa",
"Hayley",
"Hedley",
"Hedwig",
"Henry",
"Hilda",
"Holly",
"Holmes",
"Honorato",
"Hop",
"Hoyt",
"Huppy",
"Hunter",
"Hyatt",
"Ifeoma",
"Ignatius",
"Igor",
"Illiana",
"Imani",
"Indira",
"Inga",
"Irma",
"Isaac",
"Isaiah",
"Ivan",
"Ivana",
"Ivor",
"Ivy",
"Jack",
"Jackson",
"Jacob",
"James",
"Jameson",
"Jana",
"Jane",
"Jaquelyn",
"Jarrod",
"Jelani",
"Jenna",
"Jeremy",
"Jermaine",
"Jerome",
"Jesse",
"Jessica",
"Joel",
"Jonah",
"Jordan",
"Jorden",
"Joseph",
"Joshua",
"Josiah",
"Judah",
"Julian",
"Julie",
"Kane",
"Kaseem",
"Keane",
"Keegan",
"Keith",
"Kennan",
"Kennedy",
"Kenyon",
"Kenzie",
"Kermit",
"Kerry",
"Kibo",
"Kim",
"Kirk",
"Kirsten",
"Knox",
"Laith",
"Lamar",
"Lani",
"Lareina",
"Lawrence",
"Leah",
"Lee",
"Leon",
"Leonard",
"Len",
"Leo",
"Lester",
"Lev",
"Lewis",
"Lillian",
"Linus",
"Lionel",
"Lisandra",
"Logan",
"Luke",
"Lyle",
"Madeson",
"Magee",
"Maisie",
"Maite",
"Malachi",
"Malik",
"Mannix",
"Mara",
"Margaret",
"Marsden",
"Marshall",
"Martena",
"Martin",
"Marvin",
"Mason",
"Maxine",
"Maxwell",
"Mc",
"Melinda",
"Mercedes",
"Michael",
"Miriam",
"Mufutau",
"Myles",
"Nash",
"Nasim",
"Natalie",
"Nathan",
"Nathaniel",
"Nehru",
"Neil",
"Nero",
"Nevada",
"Neville",
"Nissim",
"Noble",
"Nolan",
"Norman",
"Nyssa",
"Ocean",
"Octavius",
"Oleg",
"Oliver",
"Olivia",
"Oren",
"Orli",
"Orson",
"Oscar",
"Owen",
"Paki",
"Palmer",
"Pearl",
"Penelope",
"Petra",
"Phelan",
"Philip",
"Phillip",
"Phyllis",
"Plato",
"Porter",
"Preston",
"Quail",
"Quemby",
"Quinn",
"Quintessa",
"Quynn",
"Rajah",
"Randall",
"Raphael",
"Rashad",
"Ray",
"Raymond",
"Reed",
"Reuben",
"Rhonda",
"Richard",
"Robert",
"Ronan",
"Rooney",
"Ross",
"Roth",
"Rudyard",
"Samson",
"Samuel",
"Sean",
"September",
"Seth",
"Shad",
"Shafira",
"Shannon",
"Shay",
"Shya",
"Sigourney",
"Solomon",
"Stacy",
"Steel",
"Stella",
"Steven",
"Stewart",
"Stone",
"Stuart",
"Summer",
"Sybil",
"Sylvester",
"Ta",
"Talon",
"Tamara",
"Tarik",
"Tasha",
"Tate",
"Tatyana",
"Thaddeus",
"Theodore",
"Todd",
"Travis",
"Trevor",
"Tyler",
"Tyrone",
"Ulric",
"Ulysses",
"Uriah",
"Uriel",
"Ursa",
"Valentine",
"Vance",
"Vaughan",
"Veronica",
"Vincent",
"Vladimir",
"Wade",
"Walker",
"Wallace",
"Wanda",
"Wang",
"Warren",
"Wesley",
"Wesley",
"Wilma",
"Xanthus",
"Xavier",
"Xenos",
"Yen",
"Yoko",
"Yoshio",
"Yuli",
"Zachery",
"Zahir",
"Zane",
"Zephania" };
                      
                  int cont = 0;
                        while (cont < num) {
                            int x = generateNumber(0, 383 - cont);
                            arr[cont] = nombres[x];
                            nombres.erase(nombres.begin() + x);
                            cont++;
                        }
                        return arr;
}
string crearApellido() {
    string apellidos[] = { "French",
                          "Bright",
                          "Mcmahon",
                          "Bowen",
                          "Garza",
                          "Mcneil",
                          "Garcia",
                          "Terry",
                          "Sutton",
                          "Fitzgerald",
                          "Bass",
                          "Hunter",
                          "Clemons",
                          "Dickerson",
                          "Olsen",
                          "Morse",
                          "Fletcher",
                          "Washington",
                          "Head",
                          "Kinney",
                          "Gallagher",
                          "Navarro",
                          "Mccullough",
                          "Whitfield",
                          "Lynch",
                          "Rodgers",
                          "Dominguez",
                          "Rowland",
                          "Davenport",
                          "Simon",
                          "Morton",
                          "Wells",
                          "Vincent",
                          "Curtis",
                          "Preston",
                          "Glenn",
                          "Howard",
                          "Hooper",
                          "Pennington",
                          "Tate",
                          "Marsh",
                          "Dorsey",
                          "Levy",
                          "Huff",
                          "Rogers",
                          "Bryan",
                          "Herring",
                          "Kirkland",
                          "Dyer",
                          "Delacruz",
                          "Joyner",
                          "Roman",
                          "Cook",
                          "Jacobs",
                          "Morgan",
                          "Shaw",
                          "Patton",
                          "Brooks",
                          "Klein",
                          "Shaw",
                          "Burgess",
                          "Morse",
                          "Sparks",
                          "Mayo",
                          "Dudley",
                          "Petty",
                          "Sutton",
                          "Small",
                          "Obrien",
                          "Doyle",
                          "Edwards",
                          "Harding",
                          "Salazar",
                          "Terry",
                          "Gillespie",
                          "Dyer",
                          "Finch",
                          "Snyder",
                          "Abbott",
                          "May",
                          "Garner",
                          "Mitchell",
                          "Moody",
                          "Briggs",
                          "Mccullough",
                          "Travis",
                          "Saunders",
                          "Ramsey",
                          "Bryan",
                          "Duran",
                          "Baker",
                          "Rose",
                          "Johnson",
                          "Alford",
                          "Decker",
                          "Everett",
                          "Wade",
                          "Monroe",
                          "Juarez",
                          "Langley",
                          "Briggs",
                          "Warner",
                          "Sheppard",
                          "Perkins",
                          "Cox",
                          "West",
                          "Malone",
                          "Wyatt",
                          "Morin",
                          "Bradshaw",
                          "Flynn",
                          "Rogers",
                          "Benton",
                          "Goodman",
                          "Hooper",
                          "Gray",
                          "David",
                          "Ray",
                          "Hernandez",
                          "Ball",
                          "Boone",
                          "Mclaughlin",
                          "Houston",
                          "Hartman",
                          "Sargent",
                          "Wooten",
                          "Simon",
                          "Hurley",
                          "Joyner",
                          "Silva",
                          "Mccall",
                          "Stevens",
                          "Copeland",
                          "Burton",
                          "Chase",
                          "Barrett",
                          "Cherry",
                          "Carter",
                          "Pearson",
                          "Mercado",
                          "Stanton",
                          "Shepherd",
                          "Johnston",
                          "Ramos",
                          "Hines",
                          "Melendez",
                          "Dorsey",
                          "Mendez",
                          "Russo",
                          "Stanton",
                          "Grimes",
                          "Cervantes",
                          "Jennings",
                          "Boone",
                          "Jacobson",
                          "Peters",
                          "Burnett",
                          "Flowers",
                          "Perry",
                          "Gray",
                          "Lawson",
                          "Barnett",
                          "Skinner",
                          "Finley",
                          "Vincent",
                          "Mcdaniel",
                          "Simpson",
                          "Morales",
                          "Farley",
                          "Gomez",
                          "Wise",
                          "Dale",
                          "Galloway",
                          "Burt",
                          "Gordon",
                          "Copeland",
                          "Mitchell",
                          "Wilkins",
                          "Clemons",
                          "Swanson",
                          "Allen",
                          "Burgess",
                          "Bennett",
                          "Pacheco",
                          "Kim",
                          "Singleton",
                          "Bradshaw",
                          "Whitehead",
                          "Haley",
                          "Burke",
                          "Hatfield",
                          "Francis",
                          "Acevedo",
                          "Gillespie",
                          "Salinas",
                          "Berg",
                          "Curtis",
                          "Matthews",
                          "Workman",
                          "Doyle",
                          "Dominguez",
                          "Flowers",
                          "Roberts",
                          "Garrison",
                          "Dunlap",
                          "Montgomery",
                          "Goodman",
                          "Britt",
                          "Ferrell",
                          "Buchanan",
                          "Kirkland",
                          "Sloan",
                          "Mckinney",
                          "Boyer",
                          "Head",
                          "Kirkland",
                          "Hernandez",
                          "Mcconnell",
                          "William",
                          "Reid",
                          "Carlson",
                          "Cote",
                          "Caldwell",
                          "Payne",
                          "Sims",
                          "Mueller",
                          "Bray",
                          "Ferguson",
                          "Noel",
                          "Glenn",
                          "Mcgowan",
                          "Pitts",
                          "Elliott",
                          "Henson",
                          "Harrington",
                          "Hawkins",
                          "English",
                          "George",
                          "Morgan",
                          "Wynn",
                          "Boyle",
                          "Tillman",
                          "Glover",
                          "Osborn",
                          "Livingston",
                          "Middleton",
                          "Mcdowell",
                          "Lambert",
                          "Keller",
                          "Wagner",
                          "Velasquez",
                          "Delgado",
                          "Lloyd",
                          "Rios",
                          "Crosby",
                          "Cervantes",
                          "Langley",
                          "Medina",
                          "Blankenship",
                          "Nolan",
                          "Lang",
                          "Rosales",
                          "Downs",
                          "Green",
                          "Pruitt",
                          "Figueroa",
                          "Frye",
                          "Acevedo",
                          "Alvarado",
                          "Landry",
                          "Galloway",
                          "Perez",
                          "House",
                          "Curry",
                          "Rivas",
                          "Rosario",
                          "Barrera",
                          "Barnes",
                          "Prince",
                          "Burke",
                          "Johnston",
                          "Parker",
                          "Harmon",
                          "Mays",
                          "Morgan",
                          "Kemp",
                          "Snow",
                          "Goodman",
                          "Vincent",
                          "Koch",
                          "Terry",
                          "Le",
                          "Middleton",
                          "Gilliam",
                          "Nichols",
                          "Woods",
                          "Dennis",
                          "Mcfadden",
                          "Case",
                          "Neal",
                          "Sharp",
                          "Delacruz",
                          "Sanders",
                          "Freeman",
                          "Riley",
                          "Marquez",
                          "Gonzales",
                          "Molina",
                          "Knight",
                          "Willis",
                          "Harris",
                          "Guerra",
                          "Huber",
                          "Beck",
                          "Tyson",
                          "Eaton",
                          "Graves",
                          "Pollard",
                          "Madden",
                          "Freeman",
                          "Boyle",
                          "Odom",
                          "Kidd",
                          "Price",
                          "Kirkland",
                          "Haley",
                          "Mcgee",
                          "Waller",
                          "Wooten",
                          "Walters",
                          "Strong",
                          "Brennan",
                          "Lott",
                          "Noel",
                          "Beach",
                          "Hernandez",
                          "Thomas",
                          "Dunn",
                          "Nolan",
                          "Bauer",
                          "Phelps",
                          "Deleon",
                          "Peterson",
                          "Valenzuela",
                          "Hammond",
                          "Knowles",
                          "Hull",
                          "Hewitt",
                          "Carlson",
                          "Little",
                          "Blackwell",
                          "Woodard",
                          "Wiggins",
                          "Parsons",
                          "Compton",
                          "Fields",
                          "Silva",
                          "Cline",
                          "Middleton",
                          "Combs",
                          "Huber",
                          "Morrow",
                          "Gillespie",
                          "Berg",
                          "Russell",
                          "Holmes",
                          "Norman",
                          "Todd",
                          "Hawkins",
                          "Phillips",
                          "Nash",
                          "Rollins",
                          "Cash",
                          "Kline",
                          "Lancaster",
                          "Berg",
                          "Green",
                          "Munoz",
                          "Velasquez",
                          "Sheppard",
                          "Austin",
                          "Hardin",
                          "Marshall",
                          "Leonard",
                          "Dale",
                          "Tucker",
                          "Blanchard",
                          "Mckinney",
                          "Carey",
                          "Arnold",
                          "Bartlett",
                          "Stokes",
                          "Dudley",
                          "Mullins",
                          "Ashley",
                          "Vaughn",
                          "Gardner",
                          "Alvarado",
                          "Hooper",
                          "Larsen",
                          "Miranda",
                          "Schmidt",
                          "Ryan",
                          "Randall",
                          "Livingston",
                          "Sanchez",
                          "Mcdonald",
                          "Cantu",
                          "Hawkins",
                          "Sanford",
                          "Hale",
                          "Chen",
                          "Albert",
                          "Vaughan",
                          "Maxwell",
                          "Booth",
                          "Trevino",
                          "Nielsen",
                          "Livingston",
                          "English",
                          "Gutierrez",
                          "Turner",
                          "Callahan",
                          "Nguyen",
                          "House",
                          "Williamson",
                          "Larson",
                          "Gallagher",
                          "Herman",
                          "Morin",
                          "Pacheco",
                          "Harrington",
                          "Dalton",
                          "Gaines",
                          "Hester",
                          "Buckley",
                          "Britt",
                          "Floyd",
                          "Owen",
                          "Barnes",
                          "Rowe",
                          "Ford",
                          "Jennings",
                          "Calhoun",
                          "Brewer",
                          "Kidd",
                          "Gates",
                          "Wiley",
                          "Peterson",
                          "Rowe",
                          "Quinn",
                          "Sharp",
                          "Dunn",
                          "Chan",
                          "Schultz",
                          "Baird",
                          "Yang",
                          "Williamson",
                          "Bush",
                          "David",
                          "Frank",
                          "Burks",
                          "Shaw",
                          "Zimmerman",
                          "Warren",
                          "Goodman",
                          "Tran",
                          "Burt",
                          "Wyatt",
                          "Delgado",
                          "Newman",
                          "Little",
                          "Sanchez",
                          "Glover",
                          "Mathews",
                          "Bowen",
                          "Boyle",
                          "Nelson",
                          "Blake",
                          "Silva",
                          "Tillman",
                          "Love",
                          "Mccray",
                          "Haley",
                          "Duran",
                          "Cannon",
                          "Malone",
                          "Key",
                          "Carver",
                          "Albert",
                          "Knowles",
                          "Alford",
                          "Ryan",
                          "Vargas",
                          "Golden",
                          "Mcfadden",
                          "Simon",
                          "Hopper",
                          "King" };
                          return apellidos[generateNumber(0, 498)];
}

string crearPais() {
    string paises[] = {// 85 paises
 "Iraq",
 "Curaçao",
 "Zimbabwe",
 "Sudan",
 "Mali",
 "Vatican",
 "Nepal",
 "Vietnam",
 "Turkey",
 "Qatar",
 "Nigeria",
 "Bhutan",
 "Congo",
 "Fiji",
 "Samoa",
 "Lithuania",
 "Laos",
 "Cyprus",
 "Uganda",
 "Mauritius",
 "Indonesia",
 "Barbados",
 "Thailand",
 "Montenegro",
 "Emirates",
 "Panama",
 "Egypt",
 "Norway",
 "Guadeloupe",
 "Latvia",
 "Afghanistan",
 "Latvia",
 "Britain",
 "San",
 "Marino",
 "Macao",
 "Gabon",
 "Macao",
 "Colombia",
 "Guam",
 "Azerbaijan",
 "Togo",
 "Viet",
 "Nam",
 "Belgium",
 "Micronesia",
 "Benin",
 "Benin",
 "Uruguay",
 "Russia",
 "Denmark",
 "Indonesia",
 "Haiti",
 "Lesotho",
 "Kuwait",
 "Qatar",
 "France",
 "Venezuela",
 "Mauritania",
 "Malaysia",
 "Turkmenistan",
 "Bahrain",
 "Liechtenstein",
 "Libya",
 "Uzbekistan",
 "Kazakhstan",
 "Bermuda",
 "Brazil",
 "Iraq",
 "Togo",
 "Bhutan",
 "Tokelau",
 "Guatemala",
 "Tokelau",
 "Algeria",
 "Dominican",
 "Antarctica",
 "Laos",
 "Belarus",
 "Lesotho" };
    return paises[generateNumber(0,85)];
}

string* createPeliculaNombre(int num) {
    string* arr = new string [num];
     vector <string> nombresPeliculas = { "Zack and Miri",
 "Youth in Revolt",
 "You Will Meet a Tall Dark Stranger",
 "When in Rome",
 "What Happens in Vegas",
 "Water For Elephants",
 "WALL-E",
 "Waitress",
 "Waiting For Forever",
 "Valentine's Day",
 "Tyler Perry's Why Did I get Married",
 "Twilight: Breaking Dawn",
 "Twilight",
 "The Ugly Truth",
 "The Twilight Saga: New Moon",
 "The Time Traveler's Wife",
 "The Proposal",
 "The Invention of Lying",
 "The Heartbreak Kid",
 "The Duchess",
 "The Curious Case of Benjamin Button",
 "The Back-up Plan",
 "Tangled",
 "Something Borrowed",
 "She s Out of My League",
 "Sex and the City Two",
 "Sex and the City 2",
 "Sex and the City",
 "Remember Me",
 "Rachel Getting Married",
 "Penelope",
 "P.S. I Love You",
 "Over Her Dead Body",
 "Our Family Wedding",
 "One Day",
 "Not Easily Broken",
 "No Reservations",
 "Nick and Norah s Infinite Playlist",
 "New Year's Eve",
 "My Week with Marilyn",
 "Music and Lyrics",
 "Monte Carlo",
 "Miss Pettigrew Lives for a Day",
 "Midnight in Paris",
 "Marley and Me",
 "Mamma Mia!",
 "Made of Honor",
 "Love Happens",
 "Love & Other Drugs",
 "Life as We Know It",
 "License to Wed",
 "Letters to Juliet",
 "Leap Year",
 "Knocked Up",
 "Killers",
 "Just Wright",
 "Jane Eyre",
 "Its Complicated",
 "I Love You Phillip Morris",
 "High School Musical 3: Senior Year",
 "He s Just Not That Into You",
 "Good Luck Chuck",
 "Going the Distance",
 "Gnomeo and Juliet",
 "Ghosts of Girlfriends Past",
 "Four Christmases",
 "Fireproof",
 "Enchanted",
 "Dear John",
 "Beginners",
 "Across the Universe",
 "A Serious Man",
 "A Dangerous Method",
 "27 Dresses",
 "(500) Days of Summer" };
     int cont = 0;
     while (cont<num) {
         int x = generateNumber(0, 75 - cont);
         arr[cont] = nombresPeliculas[x];
         nombresPeliculas.erase(nombresPeliculas.begin() + x);
         cont++;
     }
  
    return arr;
}

string estudio() {
    string studio[] = { "CBS",
 "Universal",
 "Summit",
 "20th Century Fox",
 "Fox",
 "New Line",
 "Independent",
 "Lionsgate",
 "Warner Bros",
 "Sony",
 "Paramount",
 "The Weinstein Company",
 "Disney" };
    return studio[generateNumber(0, 13)];
}

