#pragma once
#include <stdlib.h>     /* srand, rand */
#include <time.h>       /* time */
#include <string>
#include <vector>
#include <algorithm>
using namespace std;
int generateNumber(int inferior, int superior){
    /* initialize random seed: */
    srand(time(NULL));

    /* generate secret number between inferior and superior: */
    int num = rand() % superior + inferior;

    return num;
}

string* crearNombre(int num){
    string* arr = new string[num];
vector <string> nombres = { "Uriah",
                        "Zephania",
                        "Brody",
                        "Abbot",
                        "Baker",
                        "Dolan",
                        "Beck",
                        "George",
                        "Palmer",
                        "Samson",
                        "Derek",
                        "Devin",
                        "Giacomo",
                        "Stewart",
                        "Drew",
                        "Flynn",
                        "Conan",
                        "Brian",
                        "Garrison",
                        "Plato",
                        "Marvin",
                        "Abdul",
                        "Curran",
                        "Zachary",
                        "Nasim",
                        "Raphael",
                        "Neville",
                        "Lee",
                        "Griffith",
                        "Lev",
                        "Richard",
                        "Curran",
                        "Duncan",
                        "Barrett",
                        "Hedley",
                        "Carson",
                        "Damian",
                        "Charles",
                        "Dale",
                        "Solomon",
                        "Mason",
                        "Oliver",
                        "Mannix",
                        "Kennedy",
                        "Yoshio",
                        "Samuel",
                        "Grant",
                        "Norman",
                        "Gabriel",
                        "Jesse",
                        "Owen",
                        "Nasim",
                        "Roth",
                        "Philip",
                        "Wang",
                        "Keith",
                        "Yoshio",
                        "Driscoll",
                        "Carter",
                        "Marsden",
                        "Plato",
                        "Kane",
                        "Chandler",
                        "Porter",
                        "Curran",
                        "Lee",
                        "Hyatt",
                        "Kane",
                        "Vance",
                        "Driscoll",
                        "Clarke",
                        "Alfonso",
                        "Dean",
                        "James",
                        "Driscoll",
                        "Luke",
                        "Garrett",
                        "Rashad",
                        "Ulysses",
                        "Calvin",
                        "Giacomo",
                        "Berk",
                        "Ashton",
                        "Ross",
                        "Colt",
                        "Warren",
                        "Nehru",
                        "Arsenio",
                        "Wesley",
                        "Lester",
                        "Plato",
                        "Theodore",
                        "Ivan",
                        "Colton",
                        "Garth",
                        "Richard",
                        "Oliver",
                        "Igor",
                        "Oliver",
                        "Josiah",
                        "Jordan",
                        "Byron",
                        "Jacob",
                        "Octavius",
                        "Amery",
                        "Hamish",
                        "Joel",
                        "Tarik",
                        "James",
                        "Joel",
                        "Nolan",
                        "Wesley",
                        "Steel",
                        "Zachery",
                        "Benedict",
                        "Clark",
                        "Shad",
                        "Plato",
                        "Laith",
                        "Hashim",
                        "Keegan",
                        "Honorato",
                        "Rajah",
                        "Ronan",
                        "Hedley",
                        "Emerson",
                        "Graham",
                        "Jarrod",
                        "Craig",
                        "Dean",
                        "Todd",
                        "Kennan",
                        "Hashim",
                        "Ashton",
                        "Nero",
                        "Dennis",
                        "Armando",
                        "Brock",
                        "Ulysses",
                        "Lionel",
                        "Marsden",
                        "Holmes",
                        "Tyler",
                        "Ezekiel",
                        "Finn",
                        "Isaiah",
                        "Oscar",
                        "Neil",
                        "Myles",
                        "Mufutau",
                        "Neville",
                        "Steel",
                        "Byron",
                        "Raymond",
                        "Carl",
                        "Lawrence",
                        "Orson",
                        "Bernard",
                        "Francis",
                        "Armando",
                        "Boris",
                        "Stone",
                        "Oren",
                        "Talon",
                        "Honorato",
                        "Quinn",
                        "Jerome",
                        "Jonah",
                        "Isaiah",
                        "Reuben",
                        "Nissim",
                        "Roth",
                        "Linus",
                        "Alden",
                        "Aidan",
                        "Caldwell",
                        "Hop",
                        "Brent",
                        "Paki",
                        "Marshall",
                        "Valentine",
                        "Calvin",
                        "Alec",
                        "James",
                        "Joshua",
                        "Berk",
                        "Xavier",
                        "Leo",
                        "Thaddeus",
                        "Calvin",
                        "Henry",
                        "Clayton",
                        "Wallace",
                        "August",
                        "Harrison",
                        "Ulysses",
                        "Noble",
                        "Driscoll",
                        "Branden",
                        "Sylvester",
                        "Callum",
                        "Jelani",
                        "Julian",
                        "Caleb",
                        "Donovan",
                        "Keane",
                        "Henry",
                        "Lyle",
                        "Reed",
                        "Elliott",
                        "Hashim",
                        "Giacomo",
                        "Garth",
                        "Oleg",
                        "Len",
                        "Vladimir",
                        "Wade",
                        "Emery",
                        "Harding",
                        "Preston",
                        "Jermaine",
                        "Jarrod",
                        "Honorato",
                        "Cole",
                        "Andrew",
                        "Giacomo",
                        "Callum",
                        "Xanthus",
                        "Kermit",
                        "Hedley",
                        "Malachi",
                        "Ulric",
                        "Kenyon",
                        "Burton",
                        "Declan",
                        "Hasad",
                        "Tyler",
                        "Malik",
                        "Edan",
                        "Nathan",
                        "Andrew",
                        "Connor",
                        "Ciaran",
                        "Jack",
                        "Zahir",
                        "Xenos",
                        "Phillip",
                        "Denton",
                        "Griffin",
                        "Stone",
                        "Beau",
                        "Lionel",
                        "Vincent",
                        "Colton",
                        "Hunter",
                        "August",
                        "Channing",
                        "Dominic",
                        "Robert",
                        "Clarke",
                        "Rooney",
                        "Michael",
                        "Tyrone",
                        "Chase",
                        "Amos",
                        "Isaac",
                        "Chandler",
                        "Uriel",
                        "Rooney",
                        "Laith",
                        "Ross",
                        "Valentine",
                        "Bevis",
                        "Lamar",
                        "Elton",
                        "James",
                        "Stone",
                        "Barclay",
                        "Axel",
                        "Wade",
                        "Arthur",
                        "Ethan",
                        "Jeremy",
                        "Orson",
                        "Ray",
                        "Berk",
                        "Amal",
                        "Garrett",
                        "Josiah",
                        "Grant",
                        "Dylan",
                        "Brandon",
                        "Cyrus",
                        "Martin",
                        "Zachery",
                        "Ferris",
                        "Kirk",
                        "Drew",
                        "Eaton",
                        "Jermaine",
                        "Marshall",
                        "Vaughan",
                        "Dexter",
                        "Seth",
                        "Phelan",
                        "Colorado",
                        "Elliott",
                        "Erich",
                        "Colin",
                        "Nathaniel",
                        "Dorian",
                        "Marvin",
                        "Knox",
                        "Graiden",
                        "Sean",
                        "Steven",
                        "Camden",
                        "Duncan",
                        "Acton",
                        "Lee",
                        "Christian",
                        "Jackson",
                        "Giacomo",
                        "Ivan",
                        "Kibo",
                        "Felix",
                        "Brady",
                        "Eagan",
                        "Driscoll",
                        "Zane",
                        "Hammett",
                        "Randall",
                        "Wang",
                        "Garrison",
                        "Bruce",
                        "Chandler",
                        "Alexander",
                        "Kenyon",
                        "Ignatius",
                        "Chancellor",
                        "Marsden",
                        "Gannon",
                        "Lewis",
                        "Stuart",
                        "Geoffrey",
                        "Yuli",
                        "Dennis",
                        "Jarrod",
                        "Branden",
                        "Hoyt",
                        "Joseph",
                        "Tyrone",
                        "Dane",
                        "Kaseem",
                        "Daquan",
                        "Walker",
                        "Xenos",
                        "Trevor",
                        "Logan",
                        "Maxwell",
                        "Magee",
                        "Rudyard",
                        "Judah",
                        "Tyrone",
                        "Graham",
                        "Caleb",
                        "David",
                        "Yoshio",
                        "Carl",
                        "Hu",
                        "Travis",
                        "Ray",
                        "Nash",
                        "August",
                        "Jameson",
                        "Malik",
                        "Colt",
                        "Abel",
                        "Graiden",
                        "Tate",
                        "Abel",
                        "Lamar",
                        "Tarik",
                        "James",
                        "Branden",
                        "Ivor",
                        "Byron",
                        "Shay",
                        "Destiny",
                        "Pearl",
                        "Tamara",
                        "Orli",
                        "Pearl",
                        "Jaquelyn",
                        "Audra",
                        "Veronica",
                        "Stella",
                        "Shafira",
                        "Tatyana",
                        "Germane",
                        "Martena",
                        "Hayfa",
                        "Phyllis",
                        "Natalie",
                        "Maxine",
                        "Hayley",
                        "Carly",
                        "Adele",
                        "Stacy",
                        "Fay",
                        "Leah",
                        "Hilda",
                        "Rhonda",
                        "Jessica",
                        "Claire",
                        "Penelope",
                        "Yoko",
                        "Imani",
                        "Sigourney",
                        "Galena",
                        "Hedwig",
                        "Maisie",
                        "Wilma",
                        "Mara",
                        "Yen",
                        "Cora",
                        "Kim",
                        "Kirsten",
                        "Jana",
                        "Mc",
                        "Kenzie",
                        "Dorothy",
                        "Olivia",
                        "Ocean",
                        "Summer",
                        "Ifeoma",
                        "Ursa",
                        "Jane",
                        "Stacy",
                        "Miriam",
                        "Julie",
                        "Margaret",
                        "Inga",
                        "Lani",
                        "Maite",
                        "Adria",
                        "Candice",
                        "Mercedes",
                        "Britanney",
                        "Quynn",
                        "Althea",
                        "September",
                        "Jorden",
                        "Quemby",
                        "Quintessa",
                        "Ta",
                        "Shya",
                        "Kerry",
                        "Shannon",
                        "Clementine",
                        "Freya",
                        "Tasha",
                        "Lisandra",
                        "Lareina",
                        "Quail",
                        "Sybil",
                        "Cailin",
                        "April",
                        "Ivy",
                        "Indira",
                        "Haviva",
                        "Irma",
                        "Nyssa",
                        "Madeson",
                        "Jordan",
                        "Wanda",
                        "Erica",
                        "Illiana",
                        "Jenna",
                        "Camilla",
                        "Felicia",
                        "Holly",
                        "Lareina",
                        "Petra",
                        "Nevada",
                        "Lillian",
                        "Melinda" };
                        sort(nombres.begin(), nombres.end());
                        cout << "////////////////////" << endl;
                        for (int i = 0;i < nombres.size();i++) {
                            cout << nombres[i] << endl;
                        }
                        cout << "////////////////////" << endl;
                        return arr;
                        int cont = 0;
                        while (cont < num) {
                            int x = generateNumber(0, 500 - cont);
                            arr[cont] = nombres[x];
                            nombres.erase(nombres.begin() + x);
                            cont++;
                        }
                        for (unsigned int i = 0;i < 100 - 1;i++) { //Bubble sort O(n^2)
                            int cont = 0;
                            for (unsigned int l = 0;l <100 - 1;l++) {
                                if (arr[l].compare(arr[l+1]) > 0) {
                                    swap(arr[l], arr[l + 1]);
                                    cont++;
                                }
                            }
                            if (cont == 0) break;
                        }
                        cout << "////////////////////" << endl;
                        for (int i = 0;i < 100;i++) {
                            cout<<arr[i] << endl;
                        }
                        cout << "////////////////////" << endl;
                        return arr;
}
string crearApellido() {
    string apellidos[] = { "French",
                          "Bright",
                          "Mcmahon",
                          "Bowen",
                          "Garza",
                          "Mcneil",
                          "Garcia",
                          "Terry",
                          "Sutton",
                          "Fitzgerald",
                          "Bass",
                          "Hunter",
                          "Clemons",
                          "Dickerson",
                          "Olsen",
                          "Morse",
                          "Fletcher",
                          "Washington",
                          "Head",
                          "Kinney",
                          "Gallagher",
                          "Navarro",
                          "Mccullough",
                          "Whitfield",
                          "Lynch",
                          "Rodgers",
                          "Dominguez",
                          "Rowland",
                          "Davenport",
                          "Simon",
                          "Morton",
                          "Wells",
                          "Vincent",
                          "Curtis",
                          "Preston",
                          "Glenn",
                          "Howard",
                          "Hooper",
                          "Pennington",
                          "Tate",
                          "Marsh",
                          "Dorsey",
                          "Levy",
                          "Huff",
                          "Rogers",
                          "Bryan",
                          "Herring",
                          "Kirkland",
                          "Dyer",
                          "Delacruz",
                          "Joyner",
                          "Roman",
                          "Cook",
                          "Jacobs",
                          "Morgan",
                          "Shaw",
                          "Patton",
                          "Brooks",
                          "Klein",
                          "Shaw",
                          "Burgess",
                          "Morse",
                          "Sparks",
                          "Mayo",
                          "Dudley",
                          "Petty",
                          "Sutton",
                          "Small",
                          "Obrien",
                          "Doyle",
                          "Edwards",
                          "Harding",
                          "Salazar",
                          "Terry",
                          "Gillespie",
                          "Dyer",
                          "Finch",
                          "Snyder",
                          "Abbott",
                          "May",
                          "Garner",
                          "Mitchell",
                          "Moody",
                          "Briggs",
                          "Mccullough",
                          "Travis",
                          "Saunders",
                          "Ramsey",
                          "Bryan",
                          "Duran",
                          "Baker",
                          "Rose",
                          "Johnson",
                          "Alford",
                          "Decker",
                          "Everett",
                          "Wade",
                          "Monroe",
                          "Juarez",
                          "Langley",
                          "Briggs",
                          "Warner",
                          "Sheppard",
                          "Perkins",
                          "Cox",
                          "West",
                          "Malone",
                          "Wyatt",
                          "Morin",
                          "Bradshaw",
                          "Flynn",
                          "Rogers",
                          "Benton",
                          "Goodman",
                          "Hooper",
                          "Gray",
                          "David",
                          "Ray",
                          "Hernandez",
                          "Ball",
                          "Boone",
                          "Mclaughlin",
                          "Houston",
                          "Hartman",
                          "Sargent",
                          "Wooten",
                          "Simon",
                          "Hurley",
                          "Joyner",
                          "Silva",
                          "Mccall",
                          "Stevens",
                          "Copeland",
                          "Burton",
                          "Chase",
                          "Barrett",
                          "Cherry",
                          "Carter",
                          "Pearson",
                          "Mercado",
                          "Stanton",
                          "Shepherd",
                          "Johnston",
                          "Ramos",
                          "Hines",
                          "Melendez",
                          "Dorsey",
                          "Mendez",
                          "Russo",
                          "Stanton",
                          "Grimes",
                          "Cervantes",
                          "Jennings",
                          "Boone",
                          "Jacobson",
                          "Peters",
                          "Burnett",
                          "Flowers",
                          "Perry",
                          "Gray",
                          "Lawson",
                          "Barnett",
                          "Skinner",
                          "Finley",
                          "Vincent",
                          "Mcdaniel",
                          "Simpson",
                          "Morales",
                          "Farley",
                          "Gomez",
                          "Wise",
                          "Dale",
                          "Galloway",
                          "Burt",
                          "Gordon",
                          "Copeland",
                          "Mitchell",
                          "Wilkins",
                          "Clemons",
                          "Swanson",
                          "Allen",
                          "Burgess",
                          "Bennett",
                          "Pacheco",
                          "Kim",
                          "Singleton",
                          "Bradshaw",
                          "Whitehead",
                          "Haley",
                          "Burke",
                          "Hatfield",
                          "Francis",
                          "Acevedo",
                          "Gillespie",
                          "Salinas",
                          "Berg",
                          "Curtis",
                          "Matthews",
                          "Workman",
                          "Doyle",
                          "Dominguez",
                          "Flowers",
                          "Roberts",
                          "Garrison",
                          "Dunlap",
                          "Montgomery",
                          "Goodman",
                          "Britt",
                          "Ferrell",
                          "Buchanan",
                          "Kirkland",
                          "Sloan",
                          "Mckinney",
                          "Boyer",
                          "Head",
                          "Kirkland",
                          "Hernandez",
                          "Mcconnell",
                          "William",
                          "Reid",
                          "Carlson",
                          "Cote",
                          "Caldwell",
                          "Payne",
                          "Sims",
                          "Mueller",
                          "Bray",
                          "Ferguson",
                          "Noel",
                          "Glenn",
                          "Mcgowan",
                          "Pitts",
                          "Elliott",
                          "Henson",
                          "Harrington",
                          "Hawkins",
                          "English",
                          "George",
                          "Morgan",
                          "Wynn",
                          "Boyle",
                          "Tillman",
                          "Glover",
                          "Osborn",
                          "Livingston",
                          "Middleton",
                          "Mcdowell",
                          "Lambert",
                          "Keller",
                          "Wagner",
                          "Velasquez",
                          "Delgado",
                          "Lloyd",
                          "Rios",
                          "Crosby",
                          "Cervantes",
                          "Langley",
                          "Medina",
                          "Blankenship",
                          "Nolan",
                          "Lang",
                          "Rosales",
                          "Downs",
                          "Green",
                          "Pruitt",
                          "Figueroa",
                          "Frye",
                          "Acevedo",
                          "Alvarado",
                          "Landry",
                          "Galloway",
                          "Perez",
                          "House",
                          "Curry",
                          "Rivas",
                          "Rosario",
                          "Barrera",
                          "Barnes",
                          "Prince",
                          "Burke",
                          "Johnston",
                          "Parker",
                          "Harmon",
                          "Mays",
                          "Morgan",
                          "Kemp",
                          "Snow",
                          "Goodman",
                          "Vincent",
                          "Koch",
                          "Terry",
                          "Le",
                          "Middleton",
                          "Gilliam",
                          "Nichols",
                          "Woods",
                          "Dennis",
                          "Mcfadden",
                          "Case",
                          "Neal",
                          "Sharp",
                          "Delacruz",
                          "Sanders",
                          "Freeman",
                          "Riley",
                          "Marquez",
                          "Gonzales",
                          "Molina",
                          "Knight",
                          "Willis",
                          "Harris",
                          "Guerra",
                          "Huber",
                          "Beck",
                          "Tyson",
                          "Eaton",
                          "Graves",
                          "Pollard",
                          "Madden",
                          "Freeman",
                          "Boyle",
                          "Odom",
                          "Kidd",
                          "Price",
                          "Kirkland",
                          "Haley",
                          "Mcgee",
                          "Waller",
                          "Wooten",
                          "Walters",
                          "Strong",
                          "Brennan",
                          "Lott",
                          "Noel",
                          "Beach",
                          "Hernandez",
                          "Thomas",
                          "Dunn",
                          "Nolan",
                          "Bauer",
                          "Phelps",
                          "Deleon",
                          "Peterson",
                          "Valenzuela",
                          "Hammond",
                          "Knowles",
                          "Hull",
                          "Hewitt",
                          "Carlson",
                          "Little",
                          "Blackwell",
                          "Woodard",
                          "Wiggins",
                          "Parsons",
                          "Compton",
                          "Fields",
                          "Silva",
                          "Cline",
                          "Middleton",
                          "Combs",
                          "Huber",
                          "Morrow",
                          "Gillespie",
                          "Berg",
                          "Russell",
                          "Holmes",
                          "Norman",
                          "Todd",
                          "Hawkins",
                          "Phillips",
                          "Nash",
                          "Rollins",
                          "Cash",
                          "Kline",
                          "Lancaster",
                          "Berg",
                          "Green",
                          "Munoz",
                          "Velasquez",
                          "Sheppard",
                          "Austin",
                          "Hardin",
                          "Marshall",
                          "Leonard",
                          "Dale",
                          "Tucker",
                          "Blanchard",
                          "Mckinney",
                          "Carey",
                          "Arnold",
                          "Bartlett",
                          "Stokes",
                          "Dudley",
                          "Mullins",
                          "Ashley",
                          "Vaughn",
                          "Gardner",
                          "Alvarado",
                          "Hooper",
                          "Larsen",
                          "Miranda",
                          "Schmidt",
                          "Ryan",
                          "Randall",
                          "Livingston",
                          "Sanchez",
                          "Mcdonald",
                          "Cantu",
                          "Hawkins",
                          "Sanford",
                          "Hale",
                          "Chen",
                          "Albert",
                          "Vaughan",
                          "Maxwell",
                          "Booth",
                          "Trevino",
                          "Nielsen",
                          "Livingston",
                          "English",
                          "Gutierrez",
                          "Turner",
                          "Callahan",
                          "Nguyen",
                          "House",
                          "Williamson",
                          "Larson",
                          "Gallagher",
                          "Herman",
                          "Morin",
                          "Pacheco",
                          "Harrington",
                          "Dalton",
                          "Gaines",
                          "Hester",
                          "Buckley",
                          "Britt",
                          "Floyd",
                          "Owen",
                          "Barnes",
                          "Rowe",
                          "Ford",
                          "Jennings",
                          "Calhoun",
                          "Brewer",
                          "Kidd",
                          "Gates",
                          "Wiley",
                          "Peterson",
                          "Rowe",
                          "Quinn",
                          "Sharp",
                          "Dunn",
                          "Chan",
                          "Schultz",
                          "Baird",
                          "Yang",
                          "Williamson",
                          "Bush",
                          "David",
                          "Frank",
                          "Burks",
                          "Shaw",
                          "Zimmerman",
                          "Warren",
                          "Goodman",
                          "Tran",
                          "Burt",
                          "Wyatt",
                          "Delgado",
                          "Newman",
                          "Little",
                          "Sanchez",
                          "Glover",
                          "Mathews",
                          "Bowen",
                          "Boyle",
                          "Nelson",
                          "Blake",
                          "Silva",
                          "Tillman",
                          "Love",
                          "Mccray",
                          "Haley",
                          "Duran",
                          "Cannon",
                          "Malone",
                          "Key",
                          "Carver",
                          "Albert",
                          "Knowles",
                          "Alford",
                          "Ryan",
                          "Vargas",
                          "Golden",
                          "Mcfadden",
                          "Simon",
                          "Hopper",
                          "King" };
                          return apellidos[generateNumber(0, 500)];
}

string createPais() {
    string paises[] = {// 85 paises
 "Iraq",
 "Curaçao",
 "Zimbabwe",
 "Sudan",
 "Mali",
 "Vatican",
 "Nepal",
 "Vietnam",
 "Turkey",
 "Qatar",
 "Nigeria",
 "Bhutan",
 "Congo",
 "Fiji",
 "Samoa",
 "Lithuania",
 "Laos",
 "Cyprus",
 "Uganda",
 "Mauritius",
 "Indonesia",
 "Barbados",
 "Thailand",
 "Montenegro",
 "Emirates",
 "Panama",
 "Egypt",
 "Norway",
 "Guadeloupe",
 "Latvia",
 "Afghanistan",
 "Latvia",
 "Britain",
 "San",
 " ",
 "Marino",
 "Macao",
 "Gabon",
 "Macao",
 "Colombia",
 "Guam",
 "Azerbaijan",
 "U",
 "S",
 "A",
 "Togo",
 "Viet",
 " ",
 "Nam",
 "Belgium",
 "Micronesia",
 "Benin",
 "Benin",
 "Uruguay",
 "Russia",
 "Denmark",
 "Indonesia",
 "Haiti",
 "Lesotho",
 "Kuwait",
 "Qatar",
 "France",
 "Venezuela",
 "Mauritania",
 "Malaysia",
 "Turkmenistan",
 "Bahrain",
 "Liechtenstein",
 "Libya",
 "Uzbekistan",
 "Kazakhstan",
 "Bermuda",
 "Brazil",
 "Iraq",
 "Togo",
 "Bhutan",
 "Tokelau",
 "Guatemala",
 "Tokelau",
 "Algeria",
 "Dominican",
 "Antarctica",
 "Laos",
 "Belarus",
 "Lesotho" };
    return paises[generateNumber(0,85)];
}

string* createPeliculaNombre(int num) {
    string* arr = new string [num];
     vector <string> nombresPeliculas = { "Zack and Miri",
 "Youth in Revolt",
 "You Will Meet a Tall Dark Stranger",
 "When in Rome",
 "What Happens in Vegas",
 "Water For Elephants",
 "WALL-E",
 "Waitress",
 "Waiting For Forever",
 "Valentine's Day",
 "Tyler Perry's Why Did I get Married",
 "Twilight: Breaking Dawn",
 "Twilight",
 "The Ugly Truth",
 "The Twilight Saga: New Moon",
 "The Time Traveler's Wife",
 "The Proposal",
 "The Invention of Lying",
 "The Heartbreak Kid",
 "The Duchess",
 "The Curious Case of Benjamin Button",
 "The Back-up Plan",
 "Tangled",
 "Something Borrowed",
 "She s Out of My League",
 "Sex and the City Two",
 "Sex and the City 2",
 "Sex and the City",
 "Remember Me",
 "Rachel Getting Married",
 "Penelope",
 "P.S. I Love You",
 "Over Her Dead Body",
 "Our Family Wedding",
 "One Day",
 "Not Easily Broken",
 "No Reservations",
 "Nick and Norah s Infinite Playlist",
 "New Year's Eve",
 "My Week with Marilyn",
 "Music and Lyrics",
 "Monte Carlo",
 "Miss Pettigrew Lives for a Day",
 "Midnight in Paris",
 "Marley and Me",
 "Mamma Mia!",
 "Made of Honor",
 "Love Happens",
 "Love & Other Drugs",
 "Life as We Know It",
 "License to Wed",
 "Letters to Juliet",
 "Leap Year",
 "Knocked Up",
 "Killers",
 "Just Wright",
 "Jane Eyre",
 "Its Complicated",
 "I Love You Phillip Morris",
 "High School Musical 3: Senior Year",
 "He s Just Not That Into You",
 "Good Luck Chuck",
 "Going the Distance",
 "Gnomeo and Juliet",
 "Ghosts of Girlfriends Past",
 "Four Christmases",
 "Fireproof",
 "Enchanted",
 "Dear John",
 "Beginners",
 "Across the Universe",
 "A Serious Man",
 "A Dangerous Method",
 "27 Dresses",
 "(500) Days of Summer" };
     int cont = 0;
     while (cont<num) {
         int x = generateNumber(0, 75 - cont);
         arr[cont] = nombresPeliculas[x];
         nombresPeliculas.erase(nombresPeliculas.begin() + x);
         cont++;
     }
  
    return arr;
}

string estudio() {
    string studio[] = { "CBS",
 "Universal",
 "Summit",
 "20th Century Fox",
 "Fox",
 "New Line",
 "Independent",
 "Lionsgate",
 "Warner Bros",
 "Sony",
 "Paramount",
 "The Weinstein Company",
 "Disney" };
    return studio[generateNumber(0, 13)];
}

