#pragma once
#include <stdlib.h>     /* srand, rand */
#include <time.h>       /* time */
#include <string>
#include <vector>
#include <algorithm>
#include <chrono>
using namespace std;
int generateNumber(int inferior, int superior){
    /* initialize random seed: */
    auto now = std::chrono::high_resolution_clock::now();
    auto nanos = std::chrono::duration_cast<std::chrono::nanoseconds>(now.time_since_epoch()).count();
    srand(nanos);
   
    /* generate secret number between inferior and superior: */
    int num = rand() % superior + inferior;

    return num;
}

string* crearNombre(int num){
    string* arr = new string[num];
vector <string> nombres = { "Abbot",
"Abdul",
"Abel",
"Acton",
"Adele",
"Adria",
"Aidan",
"Alden",
"Alec",
"Alexander",
"Alfonso",
"Althea",
"Amal",
"Amery",
"Amos",
"Andrew",
"April",
"Armando",
"Arsenio",
"Arthur",
"Ashton",
"Audra",
"August",
"Axel",
"Baker",
"Barclay",
"Barrett",
"Beau",
"Beck",
"Benedict",
"Berk",
"Bernard",
"Bevis",
"Boris",
"Brady",
"Branden",
"Brandon",
"Brent",
"Brian",
"Britanney",
"Brock",
"Brody",
"Bruce",
"Burton",
"Byron",
"Byron",
"Cailin",
"Caldwell",
"Caleb",
"Callum",
"Calvin",
"Camden",
"Camilla",
"Candice",
"Carl",
"Carly",
"Carson",
"Carter",
"Chancellor",
"Chandler",
"Channing",
"Charles",
"Chase",
"Christian",
"Ciaran",
"Claire",
"Clark",
"Clarke",
"Clayton",
"Clementine",
"Cole",
"Colin",
"Colorado",
"Colt",
"Colton",
"Conan",
"Connor",
"Cora",
"Craig",
"Curran",
"Cyrus",
"Dale",
"Damian",
"Dane",
"Daquan",
"David",
"Dean",
"Declan",
"Dennis",
"Denton",
"Derek",
"Destiny",
"Devin",
"Dexter",
"Dolan",
"Dominic",
"Donovan",
"Dorian",
"Dorothy",
"Drew",
"Driscoll",
"Duncan",
"Dylan",
"Eagan",
"Eaton",
"Edan",
"Elliott",
"Elton",
"Emerson",
"Emery",
"Erica",
"Erich",
"Ethan",
"Ezekiel",
"Fay",
"Felicia",
"Felix",
"Ferris",
"Finn",
"Flynn",
"Francis",
"Freya",
"Gabriel",
"Galena",
"Gannon",
"Garrett",
"Garrison",
"Garth",
"Geoffrey",
"George",
"Germane",
"Giacomo",
"Graham",
"Graiden",
"Graiden",
"Grant",
"Griffith",
"Hamish",
"Hammett",
"Harding",
"Harrison",
"Hasad",
"Hashim",
"Haviva",
"Hayfa",
"Hayley",
"Hedley",
"Hedwig",
"Henry",
"Hilda",
"Holly",
"Holmes",
"Honorato",
"Hop",
"Hoyt",
"Huppy",
"Hunter",
"Hyatt",
"Ifeoma",
"Ignatius",
"Igor",
"Illiana",
"Imani",
"Indira",
"Inga",
"Irma",
"Isaac",
"Isaiah",
"Ivan",
"Ivana",
"Ivor",
"Ivy",
"Jack",
"Jackson",
"Jacob",
"James",
"Jameson",
"Jana",
"Jane",
"Jaquelyn",
"Jarrod",
"Jelani",
"Jenna",
"Jeremy",
"Jermaine",
"Jerome",
"Jesse",
"Jessica",
"Joel",
"Jonah",
"Jordan",
"Jorden",
"Joseph",
"Joshua",
"Josiah",
"Judah",
"Julian",
"Julie",
"Kane",
"Kaseem",
"Keane",
"Keegan",
"Keith",
"Kennan",
"Kennedy",
"Kenyon",
"Kenzie",
"Kermit",
"Kerry",
"Kibo",
"Kim",
"Kirk",
"Kirsten",
"Knox",
"Laith",
"Lamar",
"Lani",
"Lareina",
"Lawrence",
"Leah",
"Lee",
"Leon",
"Leonard",
"Len",
"Leo",
"Lester",
"Lev",
"Lewis",
"Lillian",
"Linus",
"Lionel",
"Lisandra",
"Logan",
"Luke",
"Lyle",
"Madeson",
"Magee",
"Maisie",
"Maite",
"Malachi",
"Malik",
"Mannix",
"Mara",
"Margaret",
"Marsden",
"Marshall",
"Martena",
"Martin",
"Marvin",
"Mason",
"Maxine",
"Maxwell",
"Mc",
"Melinda",
"Mercedes",
"Michael",
"Miriam",
"Mufutau",
"Myles",
"Nash",
"Nasim",
"Natalie",
"Nathan",
"Nathaniel",
"Nehru",
"Neil",
"Nero",
"Nevada",
"Neville",
"Nissim",
"Noble",
"Nolan",
"Norman",
"Nyssa",
"Ocean",
"Octavius",
"Oleg",
"Oliver",
"Olivia",
"Oren",
"Orli",
"Orson",
"Oscar",
"Owen",
"Paki",
"Palmer",
"Pearl",
"Penelope",
"Petra",
"Phelan",
"Philip",
"Phillip",
"Phyllis",
"Plato",
"Porter",
"Preston",
"Quail",
"Quemby",
"Quinn",
"Quintessa",
"Quynn",
"Rajah",
"Randall",
"Raphael",
"Rashad",
"Ray",
"Raymond",
"Reed",
"Reuben",
"Rhonda",
"Richard",
"Robert",
"Ronan",
"Rooney",
"Ross",
"Roth",
"Rudyard",
"Samson",
"Samuel",
"Sean",
"September",
"Seth",
"Shad",
"Shafira",
"Shannon",
"Shay",
"Shya",
"Sigourney",
"Solomon",
"Stacy",
"Steel",
"Stella",
"Steven",
"Stewart",
"Stone",
"Stuart",
"Summer",
"Sybil",
"Sylvester",
"Ta",
"Talon",
"Tamara",
"Tarik",
"Tasha",
"Tate",
"Tatyana",
"Thaddeus",
"Theodore",
"Todd",
"Travis",
"Trevor",
"Tyler",
"Tyrone",
"Ulric",
"Ulysses",
"Uriah",
"Uriel",
"Ursa",
"Valentine",
"Vance",
"Vaughan",
"Veronica",
"Vincent",
"Vladimir",
"Wade",
"Walker",
"Wallace",
"Wanda",
"Wang",
"Warren",
"Wesley",
"Wesley",
"Wilma",
"Xanthus",
"Xavier",
"Xenos",
"Yen",
"Yoko",
"Yoshio",
"Yuli",
"Zachery",
"Zahir",
"Zane",
"Zephania" };
                      
                  int cont = 0;
                        while (cont < num) {
                            int x = generateNumber(0, 383 - cont);
                            arr[cont] = nombres[x];
                            nombres.erase(nombres.begin() + x);
                            cont++;
                        }
                        return arr;
}
string crearApellido() {
    string apellidos[] = { "French",
                          "Bright",
                          "Mcmahon",
                          "Bowen",
                          "Garza",
                          "Mcneil",
                          "Garcia",
                          "Terry",
                          "Sutton",
                          "Fitzgerald",
                          "Bass",
                          "Hunter",
                          "Clemons",
                          "Dickerson",
                          "Olsen",
                          "Morse",
                          "Fletcher",
                          "Washington",
                          "Head",
                          "Kinney",
                          "Gallagher",
                          "Navarro",
                          "Mccullough",
                          "Whitfield",
                          "Lynch",
                          "Rodgers",
                          "Dominguez",
                          "Rowland",
                          "Davenport",
                          "Simon",
                          "Morton",
                          "Wells",
                          "Vincent",
                          "Curtis",
                          "Preston",
                          "Glenn",
                          "Howard",
                          "Hooper",
                          "Pennington",
                          "Tate",
                          "Marsh",
                          "Dorsey",
                          "Levy",
                          "Huff",
                          "Rogers",
                          "Bryan",
                          "Herring",
                          "Kirkland",
                          "Dyer",
                          "Delacruz",
                          "Joyner",
                          "Roman",
                          "Cook",
                          "Jacobs",
                          "Morgan",
                          "Shaw",
                          "Patton",
                          "Brooks",
                          "Klein",
                          "Shaw",
                          "Burgess",
                          "Morse",
                          "Sparks",
                          "Mayo",
                          "Dudley",
                          "Petty",
                          "Sutton",
                          "Small",
                          "Obrien",
                          "Doyle",
                          "Edwards",
                          "Harding",
                          "Salazar",
                          "Terry",
                          "Gillespie",
                          "Dyer",
                          "Finch",
                          "Snyder",
                          "Abbott",
                          "May",
                          "Garner",
                          "Mitchell",
                          "Moody",
                          "Briggs",
                          "Mccullough",
                          "Travis",
                          "Saunders",
                          "Ramsey",
                          "Bryan",
                          "Duran",
                          "Baker",
                          "Rose",
                          "Johnson",
                          "Alford",
                          "Decker",
                          "Everett",
                          "Wade",
                          "Monroe",
                          "Juarez",
                          "Langley",
                          "Briggs",
                          "Warner",
                          "Sheppard",
                          "Perkins",
                          "Cox",
                          "West",
                          "Malone",
                          "Wyatt",
                          "Morin",
                          "Bradshaw",
                          "Flynn",
                          "Rogers",
                          "Benton",
                          "Goodman",
                          "Hooper",
                          "Gray",
                          "David",
                          "Ray",
                          "Hernandez",
                          "Ball",
                          "Boone",
                          "Mclaughlin",
                          "Houston",
                          "Hartman",
                          "Sargent",
                          "Wooten",
                          "Simon",
                          "Hurley",
                          "Joyner",
                          "Silva",
                          "Mccall",
                          "Stevens",
                          "Copeland",
                          "Burton",
                          "Chase",
                          "Barrett",
                          "Cherry",
                          "Carter",
                          "Pearson",
                          "Mercado",
                          "Stanton",
                          "Shepherd",
                          "Johnston",
                          "Ramos",
                          "Hines",
                          "Melendez",
                          "Dorsey",
                          "Mendez",
                          "Russo",
                          "Stanton",
                          "Grimes",
                          "Cervantes",
                          "Jennings",
                          "Boone",
                          "Jacobson",
                          "Peters",
                          "Burnett",
                          "Flowers",
                          "Perry",
                          "Gray",
                          "Lawson",
                          "Barnett",
                          "Skinner",
                          "Finley",
                          "Vincent",
                          "Mcdaniel",
                          "Simpson",
                          "Morales",
                          "Farley",
                          "Gomez",
                          "Wise",
                          "Dale",
                          "Galloway",
                          "Burt",
                          "Gordon",
                          "Copeland",
                          "Mitchell",
                          "Wilkins",
                          "Clemons",
                          "Swanson",
                          "Allen",
                          "Burgess",
                          "Bennett",
                          "Pacheco",
                          "Kim",
                          "Singleton",
                          "Bradshaw",
                          "Whitehead",
                          "Haley",
                          "Burke",
                          "Hatfield",
                          "Francis",
                          "Acevedo",
                          "Gillespie",
                          "Salinas",
                          "Berg",
                          "Curtis",
                          "Matthews",
                          "Workman",
                          "Doyle",
                          "Dominguez",
                          "Flowers",
                          "Roberts",
                          "Garrison",
                          "Dunlap",
                          "Montgomery",
                          "Goodman",
                          "Britt",
                          "Ferrell",
                          "Buchanan",
                          "Kirkland",
                          "Sloan",
                          "Mckinney",
                          "Boyer",
                          "Head",
                          "Kirkland",
                          "Hernandez",
                          "Mcconnell",
                          "William",
                          "Reid",
                          "Carlson",
                          "Cote",
                          "Caldwell",
                          "Payne",
                          "Sims",
                          "Mueller",
                          "Bray",
                          "Ferguson",
                          "Noel",
                          "Glenn",
                          "Mcgowan",
                          "Pitts",
                          "Elliott",
                          "Henson",
                          "Harrington",
                          "Hawkins",
                          "English",
                          "George",
                          "Morgan",
                          "Wynn",
                          "Boyle",
                          "Tillman",
                          "Glover",
                          "Osborn",
                          "Livingston",
                          "Middleton",
                          "Mcdowell",
                          "Lambert",
                          "Keller",
                          "Wagner",
                          "Velasquez",
                          "Delgado",
                          "Lloyd",
                          "Rios",
                          "Crosby",
                          "Cervantes",
                          "Langley",
                          "Medina",
                          "Blankenship",
                          "Nolan",
                          "Lang",
                          "Rosales",
                          "Downs",
                          "Green",
                          "Pruitt",
                          "Figueroa",
                          "Frye",
                          "Acevedo",
                          "Alvarado",
                          "Landry",
                          "Galloway",
                          "Perez",
                          "House",
                          "Curry",
                          "Rivas",
                          "Rosario",
                          "Barrera",
                          "Barnes",
                          "Prince",
                          "Burke",
                          "Johnston",
                          "Parker",
                          "Harmon",
                          "Mays",
                          "Morgan",
                          "Kemp",
                          "Snow",
                          "Goodman",
                          "Vincent",
                          "Koch",
                          "Terry",
                          "Le",
                          "Middleton",
                          "Gilliam",
                          "Nichols",
                          "Woods",
                          "Dennis",
                          "Mcfadden",
                          "Case",
                          "Neal",
                          "Sharp",
                          "Delacruz",
                          "Sanders",
                          "Freeman",
                          "Riley",
                          "Marquez",
                          "Gonzales",
                          "Molina",
                          "Knight",
                          "Willis",
                          "Harris",
                          "Guerra",
                          "Huber",
                          "Beck",
                          "Tyson",
                          "Eaton",
                          "Graves",
                          "Pollard",
                          "Madden",
                          "Freeman",
                          "Boyle",
                          "Odom",
                          "Kidd",
                          "Price",
                          "Kirkland",
                          "Haley",
                          "Mcgee",
                          "Waller",
                          "Wooten",
                          "Walters",
                          "Strong",
                          "Brennan",
                          "Lott",
                          "Noel",
                          "Beach",
                          "Hernandez",
                          "Thomas",
                          "Dunn",
                          "Nolan",
                          "Bauer",
                          "Phelps",
                          "Deleon",
                          "Peterson",
                          "Valenzuela",
                          "Hammond",
                          "Knowles",
                          "Hull",
                          "Hewitt",
                          "Carlson",
                          "Little",
                          "Blackwell",
                          "Woodard",
                          "Wiggins",
                          "Parsons",
                          "Compton",
                          "Fields",
                          "Silva",
                          "Cline",
                          "Middleton",
                          "Combs",
                          "Huber",
                          "Morrow",
                          "Gillespie",
                          "Berg",
                          "Russell",
                          "Holmes",
                          "Norman",
                          "Todd",
                          "Hawkins",
                          "Phillips",
                          "Nash",
                          "Rollins",
                          "Cash",
                          "Kline",
                          "Lancaster",
                          "Berg",
                          "Green",
                          "Munoz",
                          "Velasquez",
                          "Sheppard",
                          "Austin",
                          "Hardin",
                          "Marshall",
                          "Leonard",
                          "Dale",
                          "Tucker",
                          "Blanchard",
                          "Mckinney",
                          "Carey",
                          "Arnold",
                          "Bartlett",
                          "Stokes",
                          "Dudley",
                          "Mullins",
                          "Ashley",
                          "Vaughn",
                          "Gardner",
                          "Alvarado",
                          "Hooper",
                          "Larsen",
                          "Miranda",
                          "Schmidt",
                          "Ryan",
                          "Randall",
                          "Livingston",
                          "Sanchez",
                          "Mcdonald",
                          "Cantu",
                          "Hawkins",
                          "Sanford",
                          "Hale",
                          "Chen",
                          "Albert",
                          "Vaughan",
                          "Maxwell",
                          "Booth",
                          "Trevino",
                          "Nielsen",
                          "Livingston",
                          "English",
                          "Gutierrez",
                          "Turner",
                          "Callahan",
                          "Nguyen",
                          "House",
                          "Williamson",
                          "Larson",
                          "Gallagher",
                          "Herman",
                          "Morin",
                          "Pacheco",
                          "Harrington",
                          "Dalton",
                          "Gaines",
                          "Hester",
                          "Buckley",
                          "Britt",
                          "Floyd",
                          "Owen",
                          "Barnes",
                          "Rowe",
                          "Ford",
                          "Jennings",
                          "Calhoun",
                          "Brewer",
                          "Kidd",
                          "Gates",
                          "Wiley",
                          "Peterson",
                          "Rowe",
                          "Quinn",
                          "Sharp",
                          "Dunn",
                          "Chan",
                          "Schultz",
                          "Baird",
                          "Yang",
                          "Williamson",
                          "Bush",
                          "David",
                          "Frank",
                          "Burks",
                          "Shaw",
                          "Zimmerman",
                          "Warren",
                          "Goodman",
                          "Tran",
                          "Burt",
                          "Wyatt",
                          "Delgado",
                          "Newman",
                          "Little",
                          "Sanchez",
                          "Glover",
                          "Mathews",
                          "Bowen",
                          "Boyle",
                          "Nelson",
                          "Blake",
                          "Silva",
                          "Tillman",
                          "Love",
                          "Mccray",
                          "Haley",
                          "Duran",
                          "Cannon",
                          "Malone",
                          "Key",
                          "Carver",
                          "Albert",
                          "Knowles",
                          "Alford",
                          "Ryan",
                          "Vargas",
                          "Golden",
                          "Mcfadden",
                          "Simon",
                          "Hopper",
                          "King" };
                          return apellidos[generateNumber(0, 498)];
}

string crearPais() {
    string paises[] = {// 85 paises
 "Iraq",
 "Curaçao",
 "Zimbabwe",
 "Sudan",
 "Mali",
 "Vatican",
 "Nepal",
 "Vietnam",
 "Turkey",
 "Qatar",
 "Nigeria",
 "Bhutan",
 "Congo",
 "Fiji",
 "Samoa",
 "Lithuania",
 "Laos",
 "Cyprus",
 "Uganda",
 "Mauritius",
 "Indonesia",
 "Barbados",
 "Thailand",
 "Montenegro",
 "Emirates",
 "Panama",
 "Egypt",
 "Norway",
 "Guadeloupe",
 "Latvia",
 "Afghanistan",
 "Latvia",
 "Britain",
 "San",
 "Marino",
 "Macao",
 "Gabon",
 "Macao",
 "Colombia",
 "Guam",
 "Azerbaijan",
 "Togo",
 "Viet",
 "Nam",
 "Belgium",
 "Micronesia",
 "Benin",
 "Benin",
 "Uruguay",
 "Russia",
 "Denmark",
 "Indonesia",
 "Haiti",
 "Lesotho",
 "Kuwait",
 "Qatar",
 "France",
 "Venezuela",
 "Mauritania",
 "Malaysia",
 "Turkmenistan",
 "Bahrain",
 "Liechtenstein",
 "Libya",
 "Uzbekistan",
 "Kazakhstan",
 "Bermuda",
 "Brazil",
 "Iraq",
 "Togo",
 "Bhutan",
 "Tokelau",
 "Guatemala",
 "Tokelau",
 "Algeria",
 "Dominican",
 "Antarctica",
 "Laos",
 "Belarus",
 "Lesotho" };
    return paises[generateNumber(0,85)];
}

string* createPeliculaNombre(int num) {
    string* arr = new string [num];
     vector <string> nombresPeliculas = { "Zack and Miri",
 "Youth in Revolt",
 "You Will Meet a Tall Dark Stranger",
 "When in Rome",
 "What Happens in Vegas",
 "Water For Elephants",
 "WALL-E",
 "Waitress",
 "Waiting For Forever",
 "Valentine's Day",
 "Tyler Perry's Why Did I get Married",
 "Twilight: Breaking Dawn",
 "Twilight",
 "The Ugly Truth",
 "The Twilight Saga: New Moon",
 "The Time Traveler's Wife",
 "The Proposal",
 "The Invention of Lying",
 "The Heartbreak Kid",
 "The Duchess",
 "The Curious Case of Benjamin Button",
 "The Back-up Plan",
 "Tangled",
 "Something Borrowed",
 "She s Out of My League",
 "Sex and the City Two",
 "Sex and the City 2",
 "Sex and the City",
 "Remember Me",
 "Rachel Getting Married",
 "Penelope",
 "P.S. I Love You",
 "Over Her Dead Body",
 "Our Family Wedding",
 "One Day",
 "Not Easily Broken",
 "No Reservations",
 "Nick and Norah s Infinite Playlist",
 "New Year's Eve",
 "My Week with Marilyn",
 "Music and Lyrics",
 "Monte Carlo",
 "Miss Pettigrew Lives for a Day",
 "Midnight in Paris",
 "Marley and Me",
 "Mamma Mia!",
 "Made of Honor",
 "Love Happens",
 "Love & Other Drugs",
 "Life as We Know It",
 "License to Wed",
 "Letters to Juliet",
 "Leap Year",
 "Knocked Up",
 "Killers",
 "Just Wright",
 "Jane Eyre",
 "Its Complicated",
 "I Love You Phillip Morris",
 "High School Musical 3: Senior Year",
 "He s Just Not That Into You",
 "Good Luck Chuck",
 "Going the Distance",
 "Gnomeo and Juliet",
 "Ghosts of Girlfriends Past",
 "Four Christmases",
 "Fireproof",
 "Enchanted",
 "Dear John",
 "Beginners",
 "Across the Universe",
 "A Serious Man",
 "A Dangerous Method",
 "27 Dresses",
 "(500) Days of Summer" };
     int cont = 0;
     while (cont<num) {
         int x = generateNumber(0, 75 - cont);
         arr[cont] = nombresPeliculas[x];
         nombresPeliculas.erase(nombresPeliculas.begin() + x);
         cont++;
     }
  
    return arr;
}

string estudio() {
    string studio[] = { "CBS",
 "Universal",
 "Summit",
 "20th Century Fox",
 "Fox",
 "New Line",
 "Independent",
 "Lionsgate",
 "Warner Bros",
 "Sony",
 "Paramount",
 "The Weinstein Company",
 "Disney" };
    return studio[generateNumber(0, 13)];
}


vector <pair<string, string>> crearCancion(int num) {
    vector <pair<string, string>> arr;
    vector <pair<string, string>> nombres = { { "God's Plan","Drake" },
    { "SAD!","XXXTENTACION" },
    { "rockstar (feat. 21 Savage)","Post Malone" },
    { "Psycho (feat. Ty Dolla $ign)","Post Malone" },
    { "In My Feelings","Drake" },
    { "Better Now","Post Malone" },
    { "I Like It","Cardi B" },
    { "One Kiss (with Dua Lipa)","Calvin Harris" },
    { "IDGAF","Dua Lipa" },
    { "FRIENDS","Marshmello" },
    { "Havana","Camila Cabello" },
    { "Lucid Dreams","Juice WRLD" },
    { "Nice For What","Drake" },
    { "Girls Like You (feat. Cardi B)","Maroon 5" },
    { "The Middle","Zedd" },
    { "All The Stars (with SZA)","Kendrick Lamar" },
    { "no tears left to cry","Ariana Grande" },
    { "X","Nicky Jam" },
    { "Moonlight","XXXTENTACION" },
    { "Look Alive (feat. Drake)","BlocBoy JB" },
    { "These Days","Rudimental" },
    { "Te Bot? - Remix","Nio Garcia" },
    { "Mine","Bazzi" },
    { "Youngblood","5 Seconds of Summer" },
    { "New Rules","Dua Lipa" },
    { "Shape of You","Ed Sheeran" },
    { "Love Lies (with Normani)","Khalid" },
    { "Meant to Be feat.Florida Georgia Line","Bebe Rexha" },
    { "Jocelyn Flores","XXXTENTACION" },
    { "Perfect","Ed Sheeran" },
    { "Taste (feat. Offset)","Tyga" },
    { "Solo (feat. Demi Lovato)","Clean Bandit" },
    { "I Fall Apart","Post Malone" },
    { "Nevermind","Dennis Lloyd" },
    { "?chame La Culpa","Luis Fonsi" },
    { "Eastside (with Halsey & Khalid)","benny blanco" },
    { "Never Be the Same","Camila Cabello" },
    { "Wolves","Selena Gomez" },
    { "changes","XXXTENTACION" },
    { "In My Mind","Dynoro" },
    { "River (feat. Ed Sheeran)","Eminem" },
    { "Dura","Daddy Yankee" },
    { "SICKO MODE","Travis Scott" },
    { "Thunder","Imagine Dragons" },
    { "Me Niego","Reik" },
    { "Jackie Chan","Ti?sto" },
    { "Finesse (Remix) [feat. Cardi B]","Bruno Mars" },
    { "Back To You - From 13 Reasons Why","Selena Gomez" },
    { "Let You Down","NF" },
    { "Call Out My Name","The Weeknd" },
    { "Ric Flair Drip (& Metro Boomin)","Offset" },
    { "Happier","Marshmello" },
    { "Too Good At Goodbyes","Sam Smith" },
    { "Freaky Friday (feat. Chris Brown)","Lil Dicky" },
    { "Believer","Imagine Dragons" },
    { "FEFE (feat. Nicki Minaj & Murda Beatz)","6ix9ine" },
    { "Rise","Jonas Blue" },
    { "Body (feat. brando)","Loud Luxury" },
    { "XO TOUR Llif3","Lil Uzi Vert" },
    { "Sin Pijama","Becky G" },
    { "2002","Anne-Marie" },
    { "Nonstop","Drake" },
    { "Fuck Love (feat. Trippie Redd)","XXXTENTACION" },
    { "In My Blood","Shawn Mendes" },
    { "Silence","Marshmello" },
    { "God is a woman","Ariana Grande" },
    { "D?jala que vuelva (feat. Manuel Turizo)","Piso 21" },
    { "Flames","David Guetta" },
    { "What Lovers Do","Maroon 5" },
    { "Taki Taki","DJ Snake" },
    { "Let Me Go","Hailee Steinfeld" },
    { "Feel It Still","Portugal. The Man" },
    { "Pray For Me (with Kendrick Lamar)","The Weeknd" },
    { "Walk It Talk It","Migos" },
    { "Him & I (with Halsey)","G-Eazy" },
    { "Candy Paint","Post Malone" },
    { "Congratulations","Post Malone" },
    { "Criminal","Natti Natasha" },
    { "Plug Walk","Rich The Kid" },
    { "lovely (with Khalid)","Billie Eilish" },
    { "Stir Fry","Migos" },
    { "HUMBLE.","Kendrick Lamar" },
    { "Vaina Loca","Ozuna" },
    { "Perfect Duet (Ed Sheeran & Beyonc?)","Ed Sheeran" },
    { "Coraz?n (feat. Nego do Borel)","Maluma" },
    { "Young Dumb & Broke","Khalid" },
    { "S?guelo Bailando","Ozuna" },
    { "Downtown","Anitta" },
    { "Bella","Wolfine" },
    { "Promises (with Sam Smith)","Calvin Harris" },
    { "Yes Indeed","Lil Baby" },
    { "I Like Me Better","Lauv" },
    { "This Is Me","Keala Settle" },
    { "Everybody Dies In Their Nightmares","XXXTENTACION" },
    { "Rewrite The Stars","Zac Efron" },
    { "I Miss You (feat. Julia Michaels)","Clean Bandit" },
    { "No Brainer","DJ Khaled" },
    { "Dusk Till Dawn - Radio Edit","ZAYN" },
    { "Be Alright","Dean Lewis" } };


                        int cont = 0;
                        while (cont < num) {
                            int x = generateNumber(0, 99 - cont);
                            arr.push_back(nombres[x]);
                            nombres.erase(nombres.begin() + x);
                            cont++;
                        }
                        return arr;
    }

    vector <pair<string, string>> crearJuego(int num) {
        vector <pair<string, string>> arr;
        vector <pair<string, string>> nombres = {
{"Wii Sports","Nintendo"},
{"Super Mario Bros.","Nintendo"},
{"Mario Kart Wii","Nintendo"},
{"Wii Sports Resort","Nintendo"},
{"Pokemon Red/Pokemon Blue","Nintendo"},
{"Tetris","Nintendo"},
{"New Super Mario Bros.","Nintendo"},
{"Wii Play","Nintendo"},
{"New Super Mario Bros. Wii","Nintendo"},
{"Duck Hunt","Nintendo"},
{"Nintendogs","Nintendo"},
{"Mario Kart DS","Nintendo"},
{"Pokemon Gold/Pokemon Silver","Nintendo"},
{"Wii Fit","Nintendo"},
{"Wii Fit Plus","Nintendo"},
{"Kinect Adventures!","Microsoft Game Studios"},
{"Grand Theft Auto V","Take-Two Interactive"},
{"Grand Theft Auto: San Andreas","Take-Two Interactive"},
{"Super Mario World","Nintendo"},
{"Brain Age: Train Your Brain in Minutes a Day","Nintendo"},
{"Pokemon Diamond/Pokemon Pearl","Nintendo"},
{"Super Mario Land","Nintendo"},
{"Super Mario Bros. 3","Nintendo"},
        { "Grand Theft Auto: Vice City","Take-Two Interactive" },
        { "Pokemon Ruby/Pokemon Sapphire","Nintendo" },
        { "Pokemon Black/Pokemon White","Nintendo" },
        { "Brain Age 2: More Training in Minutes a Day","Nintendo" },
        { "Gran Turismo 3: A-Spec","Sony Computer Entertainment" },
        { "Call of Duty: Modern Warfare 3","Activision" },
        { "Pokémon Yellow: Special Pikachu Edition","Nintendo" },
        { "Call of Duty: Black Ops","Activision" },
        { "Pokemon X/Pokemon Y","Nintendo" },
        { "Call of Duty: Black Ops 3","Activision" },
        { "Call of Duty: Black Ops II","Activision" },
        { "Call of Duty: Modern Warfare 2","Activision" },
        { "Grand Theft Auto III","Take-Two Interactive" },
        { "Super Smash Bros. Brawl","Nintendo" },
        { "Animal Crossing: Wild World","Nintendo" },
        { "Mario Kart 7","Nintendo" },
        { "Halo 3","Microsoft Game Studios" },
        { "Pokemon HeartGold/Pokemon SoulSilver","Nintendo" },
        { "Super Mario 64","Nintendo" },
        { "Gran Turismo 4","Sony Computer Entertainment" },
        { "Super Mario Galaxy","Nintendo" },
        { "Pokemon Omega Ruby/Pokemon Alpha Sapphire","Nintendo" },
        { "Super Mario Land 2: 6 Golden Coins","Nintendo" },
        { "Grand Theft Auto IV","Take-Two Interactive" },
        { "Gran Turismo","Sony Computer Entertainment" },
        { "Super Mario 3D Land","Nintendo" },
        { "Gran Turismo 5","Sony Computer Entertainment" },
        { "Super Mario All-Stars","Nintendo" },
        { "Pokemon FireRed/Pokemon LeafGreen","Nintendo" },
        { "Just Dance 3","Ubisoft" },
        { "Call of Duty: Ghosts","Activision" },
        { "Halo: Reach","Microsoft Game Studios" },
        { "Mario Kart 64","Nintendo" },
        { "New Super Mario Bros. 2","Nintendo" },
        { "Halo 4","Microsoft Game Studios" },
        { "Final Fantasy VII","Sony Computer Entertainment" },
        { "Just Dance 2","Ubisoft" },
        { "Gran Turismo 2","Sony Computer Entertainment" },
        { "Call of Duty 4: Modern Warfare","Activision" },
        { "Donkey Kong Country","Nintendo" },
        { "Minecraft","Microsoft Game Studios" },
        { "Animal Crossing: New Leaf","Nintendo" },
        { "Mario Party DS","Nintendo" },
        { "The Elder Scrolls V: Skyrim","Bethesda Softworks" },
        { "Super Mario Kart","Nintendo" },
        { "FIFA 16","Electronic Arts" },
        { "Wii Party","Nintendo" },
        { "Halo 2","Microsoft Game Studios" },
        { "Mario Party 8","Nintendo" },
        { "Pokemon Black 2/Pokemon White 2","Nintendo" },
        { "FIFA Soccer 13","Electronic Arts" },
        { "The Sims 3","Electronic Arts" },
        { "GoldenEye 007","Nintendo" },
        { "Mario & Sonic at the Olympic Games","Sega" },
        { "Final Fantasy X","Sony Computer Entertainment" },
        { "Final Fantasy VIII","SquareSoft" },
        { "Pokémon Platinum Version","Nintendo" },
        { "Pac-Man","Atari" },
        { "Grand Theft Auto: Liberty City Stories","Take-Two Interactive" },
        { "Super Mario Galaxy 2","Nintendo" },
        { "Star Wars Battlefront (2015)","Electronic Arts" },
        { "Call of Duty: Advanced Warfare","Activision" },
        { "The Legend of Zelda: Ocarina of Time","Nintendo" },
        { "Crash Bandicoot 2: Cortex Strikes Back","Sony Computer Entertainment" },
        { "Super Mario Bros. 2","Nintendo" },
        { "Super Smash Bros. for Wii U and 3DS","Nintendo" },
        { "Call of Duty: World at War","Activision" },
        { "Battlefield 3","Electronic Arts" },
        { "The Legend of Zelda: Twilight Princess","Nintendo" },
        { "Just Dance","Ubisoft" },
        { "Need for Speed Underground","Electronic Arts" },
        { "Tekken 3","Sony Computer Entertainment" },
        { "Crash Bandicoot 3: Warped","Sony Computer Entertainment" },
        { "Super Smash Bros. Melee","Nintendo" },
        { "Mario Kart 8","Nintendo" },
        { "Fallout 4","Bethesda Softworks" },
        { "Mario Kart: Double Dash!!","Nintendo" },
        { "Just Dance 4","Ubisoft" },
        { "FIFA 14","Electronic Arts" },
        { "Need for Speed Underground 2","Electronic Arts" },
        { "Medal of Honor: Frontline","Electronic Arts" },
        { "Uncharted 3: Drake's Deception","Sony Computer Entertainment" },
        { "Crash Bandicoot","Sony Computer Entertainment" },
        { "Zumba Fitness","505 Games" },
        { "Gears of War 2","Microsoft Game Studios" },
        { "Uncharted 2: Among Thieves","Sony Computer Entertainment" },
        { "FIFA 12","Electronic Arts" },
        { "Big Brain Academy","Nintendo" },
        { "Red Dead Redemption","Take-Two Interactive" },
        { "FIFA 15","Electronic Arts" },
        { "Donkey Kong Country Returns","Nintendo" },
        { "The Legend of Zelda","Nintendo" },
        { "Assassin's Creed III","Ubisoft" },
        { "Halo: Combat Evolved","Microsoft Game Studios" },
        { "Pokémon Emerald Version","Nintendo" },
        { "Kingdom Hearts","Sony Computer Entertainment" },
        { "Pokémon Crystal Version","Nintendo" },
        { "Halo 3: ODST","Microsoft Game Studios" },
        { "Super Mario Sunshine","Nintendo" },
        { "Street Fighter II: The World Warrior","Capcom" },
        { "World of Warcraft","Activision" },
        { "Driver","GT Interactive" },
        { "Kinect Sports","Microsoft Game Studios" },
        { "Gears of War 3","Microsoft Game Studios" },
        { "Gears of War","Microsoft Game Studios" },
        { "Metal Gear Solid 2: Sons of Liberty","Konami Digital Entertainment" },
        { "Sonic the Hedgehog 2","Sega" },
        { "Metal Gear Solid 4: Guns of the Patriots","Konami Digital Entertainment" },
        { "Metal Gear Solid","Konami Digital Entertainment" },
        { "The Last of Us","Sony Computer Entertainment Europe" },
        { "Final Fantasy XII","Square Enix" },
        { "LittleBigPlanet","Sony Computer Entertainment" },
        { "Dragon Quest IX: Sentinels of the Starry Skies","Nintendo" },
        { "LEGO Star Wars: The Complete Saga","LucasArts" },
        { "Resident Evil 2","Virgin Interactive" },
        { "Tekken 2","Sony Computer Entertainment" },
        { "Cooking Mama","505 Games" },
        { "Destiny","Activision" },
        { "Assassin's Creed II","Ubisoft" },
        { "Super Smash Bros.","Nintendo" },
        { "Assassin's Creed","Ubisoft" },
        { "Batman: Arkham City","Warner Bros. Interactive Entertainment" },
        { "Forza Motorsport 3","Microsoft Game Studios" },
        { "Monster Hunter Freedom Unite","Capcom" },
        { "Super Mario Advance","Nintendo" },
        { "Mario Kart: Super Circuit","Nintendo" },
        { "Pokemon Stadium","Nintendo" },
        { "Crash Bandicoot: The Wrath of Cortex","Universal Interactive" },
        { "Final Fantasy XIII","Square Enix" },
        { "Dr. Mario","Nintendo" },
        { "Pokemon Pinball","Nintendo" },
        { "Final Fantasy IX","SquareSoft" },
        { "Final Fantasy X-2","Electronic Arts" },
        { "Donkey Kong 64","Nintendo" },
        { "Professor Layton and the Curious Village","Nintendo" },
        { "Tomb Raider II","Eidos Interactive" },
        { "Madden NFL 2004","Electronic Arts" },
        { "Dragon Quest VIII: Journey of the Cursed King","Square Enix" },
        { "Diablo III","Activision" },
        { "New Super Mario Bros. U","Nintendo" },
        { "Super Mario Land 3: Wario Land","Nintendo" },
        { "The Legend of Zelda: Phantom Hourglass","Nintendo" },
        { "Donkey Kong Country 2: Diddy's Kong Quest","Nintendo" },
        { "Tomodachi Life","Nintendo" },
        { "Medal of Honor: Rising Sun","Electronic Arts" },
        { "Kirby's Dream Land","Nintendo" },
        { "Fable III","Microsoft Game Studios" },
        { "Microsoft Flight Simulator","Microsoft Game Studios" },
        { "Guitar Hero II","RedOctane" },
        { "Resident Evil 5","Capcom" },
        { "Grand Theft Auto: Vice City Stories","Take-Two Interactive" },
        { "FIFA Soccer 11","Electronic Arts" },
        { "Resident Evil","Virgin Interactive" },
        { "Tony Hawk's Pro Skater","Activision" },
        { "Warzone 2100","Eidos Interactive" },
        { "Spyro the Dragon","Sony Computer Entertainment" },
        { "Link's Crossbow Training","Nintendo" },
        { "Guitar Hero III: Legends of Rock","Activision" },
        { "Fallout 3","Bethesda Softworks" },
        { "Pokemon Mystery Dungeon: Explorer","Nintendo" },
        { "Uncharted: Drake's Fortune","Sony Computer Entertainment" },
        { "Madden NFL 06","Electronic Arts" },
        { "Diddy Kong Racing","Nintendo" },
        { "Monster Hunter Freedom 3","Capcom" },
        { "God of War III","Sony Computer Entertainment" },
        { "StarCraft II: Wings of Liberty","Activision" },
        { "Crash Team Racing","Sony Computer Entertainment" },
        { "FIFA 17","Electronic Arts" },
        { "Driver 2","Atari" },
        { "The Simpsons: Hit & Run","Vivendi Games" },
        { "Tony Hawk's Pro Skater 2","Activision" },
        { "Animal Crossing: City Folk","Nintendo" },
        { "The Lord of the Rings: The Two Towers","Electronic Arts" },
        { "Forza Motorsport 4","Microsoft Game Studios" },
        { "Tomb Raider","Eidos Interactive" },
        { "The Legend of Zelda: A Link to the Past","Nintendo" },
        { "The Legend of Zelda: The Wind Waker","Nintendo" },
        { "Mario & Sonic at the Olympic Winter Games","Sega" },
        { "Luigi's Mansion: Dark Moon","Nintendo" },
        { "Splatoon","Nintendo" },
        { "Madden NFL 2005","Electronic Arts" },
        { "Pitfall!","Activision" },
        { "Madden NFL 07","Electronic Arts" },
        { "Spider-Man: The Movie","Activision" },
        { "Dragon Quest VII: Warriors of Eden","Enix Corporation" },
        { "Uncharted: The Nathan Drake Collec","Sony Computer Entertainment" },
        { "God of War","Sony Computer Entertainment" },
        { "Nintendo Land","Nintendo" },
        { "Michael Jackson: The Experience","Ubisoft" },
        { "Tony Hawk's Pro Skater 3","Activision" },
        { "Winning 11: PESoccer 2007","Konami Digital Entertainment" },
        { "The Elder Scrolls IV: Oblivion","Take-Two Interactive" },
        { "Zelda II: The Adventure of Link","Nintendo" },
        { "Need for Speed: Most Wanted","Electronic Arts" },
        { "Resistance: Fall of Man","Sony Computer Entertainment" },
        { "Sonic the Hedgehog","Sega" },
        { "Kingdom Hearts II","Square Enix" },
        { "Asteroids","Atari" },
        { "Fable II","Microsoft Game Studios" },
        { "Halo 5: Guardians","Microsoft Game Studios" },
        { "Super Mario 3D World","Nintendo" },
        { "Batman: Arkham Asylum","Eidos Interactive" },
        { "Assassin's Creed: Revelations","Ubisoft" },
        { "Namco Museum","Namco Bandai Games" },
        { "Metal Gear Solid 3: Snake Eater","Konami Digital Entertainment" },
        { "Daxter","Sony Computer Entertainment" },
        { "Warcraft II: Tides of Darkness","Activision" },
        { "FIFA Soccer 06","Electronic Arts" },
        { "EyeToy Play","Sony Computer Entertainment" },
        { "Uncharted 4: A Thief's End","Sony Computer Entertainment" },
        { "Gran Turismo 5 Prologue","Sony Computer Entertainment" },
        { "Street Fighter IV","Capcom" },
        { "Teenage Mutant Ninja Turtles","Palcom" },
        { "Excitebike","Nintendo" },
        { "Frogger","Hasbro Interactive" },
        { "Madden NFL 2003","Electronic Arts" },
        { "Watch Dogs","Ubisoft" },
        { "Half-Life","Vivendi Games" },
        { "Super Mario World 2: Yoshi's Island","Nintendo" },
        { "FIFA Soccer 07","Electronic Arts" },
        { "The Legend of Zelda: Skyward Sword","Nintendo" },
        { "Street Fighter II Turbo","Capcom" },
        { "Carnival Games","Take-Two Interactive" },
        { "World of Warcraft: The Burning Crusade","Activision" },
        { "Fallout: New Vegas","Bethesda Softworks" },
        { "God of War II","Sony Computer Entertainment" },
        { "Forza Motorsport 2","Microsoft Game Studios" },
        { "World Soccer Winning 11-9","Konami Digital Entertainment" },
        { "Namco Museum Vol.3","Sony Computer Entertainment" },
        { "Tekken Tag Tournament","Namco Bandai Games" },
        { "Far Cry 4","Ubisoft" },
        { "Star Fox 64","Nintendo" },
        { "Golf","Nintendo" },
        { "Professor Layton and the Diabolical Box","Nintendo" },
        { "Left 4 Dead 2","Electronic Arts" },
        { "Namco Museum: 50th Anniversary","Namco Bandai Games" },
        { "EA Sports Active","Electronic Arts" },
        { "Assassin's Creed: Unity","Ubisoft" },
        { "Donkey Kong Land","Nintendo" },
        { "Tony Hawk's Underground","Activision" },
        { "Assassin's Creed IV: Black Flag","Ubisoft" },
        { "Monster Hunter 4 Ultimate","Nintendo" },
        { "MotorStorm","Sony Computer Entertainment" },
        { "Tekken 5","Namco Bandai Games" },
        { "Dragon Warrior III","Enix Corporation" },
        { "Sports Champions","Sony Computer Entertainment" },
        { "NBA 2K16","Take-Two Interactive" },
        { "World Soccer Eleven 8 .Int","Konami Digital Entertainment" },
        { "Flash Focus: Vision Training in Minutes a Day","Nintendo" },
        { "Namco Museum Vol.1","Sony Computer Entertainment" },
        { "The Legend of Zelda: Link's Awakening","Nintendo" },
        { "Mario & Luigi: Bowser's Inside Story","Nintendo" },
        { "Big Brain Academy: Wii Degree","Nintendo" },
        { "Nintendogs + cats","Nintendo" },
        { "Batman: Arkham Knight","Warner Bros. Interactive Entertainment" },
        { "Mario & Sonic at the London 2012 Olympic Games","Sega" },
        { "LEGO Indiana Jones: The Original Adventures","Activision" },
        { "Resident Evil Director's Cut","Virgin Interactive" },
        { "Ratchet & Clank: Size Matters","Sony Computer Entertainment" },
        { "Just Dance 2014","Ubisoft" },
        { "The Sims: Unleashed","Electronic Arts" },
        { "Super Paper Mario","Nintendo" },
        { "Harry Potter and the Sorcerer's Stone","Electronic Arts" },
        { "The Witcher 3: Wild Hunt","Namco Bandai Games" },
        { "Resident Evil 3: Nemesis","Eidos Interactive" },
        { "Spyro: Year of the Dragon","Sony Computer Entertainment" },
        { "FIFA Soccer 2005","Electronic Arts" },
        { "Pokémon Trading Card Game","Nintendo" },
        { "Battlefield 4","Electronic Arts" },
        { "MySims","Electronic Arts" },
        { "Friend Collection","Nintendo" },
        { "Tony Hawk's Pro Skater 4","Activision" },
        { "Midnight Club 3: DUB Edition","Take-Two Interactive" },
        { "Banjo-Kazooie","Nintendo" },
        { "SOCOM: U.S. Navy SEALs","Sony Computer Entertainment" },
        { "Guitar Hero: World Tour","Activision" },
        { "Gran Turismo 6","Sony Computer Entertainment" },
        { "Jak and Daxter: The Precursor Legacy","Sony Computer Entertainment" },
        { "Pokemon Snap","Nintendo" },
        { "FIFA Soccer 10","Electronic Arts" },
        { "Pro Evolution Soccer 2008","Konami Digital Entertainment" },
        { "Resident Evil 4","Capcom" },
        { "Tom Clancy's The Division","Ubisoft" },
        { "Star Wars: Battlefront","LucasArts" },
        { "Doom II: Hell on Earth","Virgin Interactive" },
        { "The Simpsons: Road Rage","Electronic Arts" },
        { "Cooking Mama 2: Dinner With Friends","505 Games" },
        { "Luigi's Mansion","Nintendo" },
        { "Star Wars: Battlefront II","LucasArts" },
        { "WWF SmackDown!","THQ" },
        { "Croc: Legend of the Gobbos","Fox Interactive" },
        { "The Getaway","Sony Computer Entertainment" },
        { "Tomb Raider III: Adventures of Lara Croft","Eidos Interactive" },
        { "James Bond 007: Agent Under Fire","Electronic Arts" },
        { "LEGO Star Wars: The Video Game","Eidos Interactive" },
        { "Rugrats in Paris: The Movie","THQ" },
        { "Spyro 2: Ripto's Rage!","Sony Computer Entertainment" },
        { "Left 4 Dead","Electronic Arts" },
        { "Donkey Kong Country 3: Dixie Kong's Double Trouble!","Nintendo" },
        { "Assassin's Creed: Brotherhood","Ubisoft" },
        { "Kung Fu","Nintendo" },
        { "Clubhouse Games","Nintendo" },
        { "FIFA Soccer 2004","Electronic Arts" },
        { "Battlefield: Bad Company 2","Electronic Arts" },
        { "Guitar Hero: On Tour","Activision" },
        { "Far Cry 3","Ubisoft" },
        { "Monster Hunter 4","Capcom" },
        { "Borderlands","Take-Two Interactive" },
        { "Tekken 4","Namco Bandai Games" },
        { "LittleBigPlanet 2","Sony Computer Entertainment" },
        { "Grand Theft Auto 2","Take-Two Interactive" },
        { "Final Fantasy III","SquareSoft" },
        { "Spider-Man 2","Activision" },
        { "F-1 Race","Nintendo" },
        { "FIFA Soccer 2003","Electronic Arts" },
        { "Crash Bash","Sony Computer Entertainment" },
        { "LEGO Batman: The Videogame","Warner Bros. Interactive Entertainment" },
        { "Metal Gear Solid V: The Phantom Pain","Konami Digital Entertainment" },
        { "The Legend of Zelda: Spirit Tracks","Nintendo" },
        { "WWF War Zone","Acclaim Entertainment" },
        { "The Legend of Zelda: Majora's Mask","Nintendo" },
        { "Professor Layton and the Unwound Future","Nintendo" },
        { "Rugrats: Search For Reptar","THQ" },
        { "English Training: Have Fun Improving Your Skills!","Nintendo" },
        { "Harry Potter and the Chamber of Secrets","Electronic Arts" },
        { "SimCity","Nintendo" },
        { "Resident Evil 6","Capcom" },
        { "Dragon Age: Inquisition","Electronic Arts" },
        { "Sonic Classic Collection","Sega" },
        { "Spyro: Enter the Dragonfly","Universal Interactive" },
        { "Devil May Cry 2","Capcom" },
        { "Burnout Paradise","Electronic Arts" },
{ "E.T.: The Extra Terrestrial","Atari" } };
    int cont = 0;
    while (cont < num) {
        int x = generateNumber(0, 356 - cont);
        arr.push_back(nombres[x]);
        nombres.erase(nombres.begin() + x);
        cont++;
    }
        return arr;
    }